---
- hosts: docker
  become: true
  remote_user: vagrant
  vars:
    - remote_dir: /home/vagrant
    - local_dir: /var/lib/jenkins/workspace/02_second-pipeline
    - remote_user: vagrant
  tasks:
  - name: stop if we have old docker container
    command: docker stop demo
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm demo
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi demo
    ignore_errors: yes

  - name: copying Dockerfile
    become: true
    copy:
      src: "{{ local_dir }}/Dockerfile"
      dest: "{{ remote_dir }}"
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"

  - name: "Copying the jar"
    copy: src={{item}} dest="{{ remote_dir }}/demo.jar"  owner="{{ remote_user }}" group="{{ remote_user }}" mode=0755
    with_fileglob: "{{ local_dir }}/target/*.jar"

  - name: building docker image using jar file
    command: docker build -t demo .
    args:
      chdir: "{{ remote_dir }}"

  - name: creating docker conteneur
    command: docker run -d --name demo -p 8080:8080 demo
    
  - name: Install docker-py
    pip: name=docker-py version=1.9.0

  - name: Log into DockerHub
    docker_login:
      username: doum167
      password: formation167
      email: formation167@gmail.com

  - name: Tag and push to docker hub
    docker_image:
      name: demo:latest
      repository: doum167/boot:latest
      push: yes
      source: local

  - name: Log out of DockerHub
    docker_login:
      state: absent
      email: formation167@gmail.com
